import type { Metadata } from "next";
import { Inter, Geist } from "next/font/google";
import "./globals.css";
import { ProviderQueryClient } from "./provider";
import { ReactQueryDevtools } from "@tanstack/react-query-devtools";
import { cn } from "@/lib/utils";

const geist = Geist({subsets:['latin'],variable:'--font-sans'});

const InterFont = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

export const metadata: Metadata = {
  title: "SmartHelp",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html lang="en" className={cn("h-full", "antialiased", InterFont.className, "font-sans", geist.variable)}>
      <ProviderQueryClient>
        <body className="min-h-full flex flex-col">{children}</body>
        <ReactQueryDevtools initialIsOpen={false} />
      </ProviderQueryClient>
    </html>
  );
}
